basic.forever(function () {
    cyberbot.connect()
    cyberbot.write_digital(20, 1)
    basic.pause(500)
    cyberbot.write_digital(20, 0)
    basic.pause(500)
    cyberbot.write_digital(21, 1)
    basic.pause(500)
    cyberbot.write_digital(21, 0)
    basic.pause(500)
})
